# Generated by Django 2.1.7 on 2019-03-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='DegreeCourse',
        ),
    ]
