# Generated by Django 2.1.7 on 2019-03-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190319_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='examgiven',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.Course'),
        ),
        migrations.AddField(
            model_name='degreecourse',
            name='courses',
            field=models.ManyToManyField(to='chat.Course'),
        ),
    ]
