# Generated by Django 2.1.7 on 2019-03-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190319_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreecourse',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='chat.Course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Professor'),
        ),
        migrations.AlterField(
            model_name='examgiven',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Course'),
        ),
        migrations.AlterField(
            model_name='examgiven',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Student'),
        ),
        migrations.AlterField(
            model_name='examsubscription',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Exam'),
        ),
        migrations.AlterField(
            model_name='examsubscription',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.DegreeCourse'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Student'),
        ),
    ]
