# Generated by Django 2.1.7 on 2019-03-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190319_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='entities',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='score_top_intent',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sentiment_analysis',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='top_scoring_intent',
        ),
        migrations.AddField(
            model_name='message',
            name='entities',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='score_top_intent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sentiment_analysis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='top_scoring_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
