# Generated by Django 2.1.7 on 2019-03-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20190319_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='vodafone_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
