# Generated by Django 2.1.7 on 2019-03-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20190319_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cfu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Course'),
        ),
    ]
