# Generated by Django 2.1.7 on 2019-03-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20190320_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
